title: Messing around
author: GitHub User
email: franklinchen@franklinchen.com
description: > # this means to ignore newlines until "baseurl:"
  Messing around with GitHub pages.
  Another sentence.

# social links
twitter_username: FranklinChen # DO NOT include the @ character, or else the build will fail!
github_username:  FranklinChen # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
thema: minima
